### ISSUE TITLE
Add video recommendation engine from KillrVideo hackathon

### ISSUE THREAD

**Issue by SonicDMG** [KillrVideo/killrvideo-java#18]

**Comment by stamhankar999** [comment]
The current state is a little wonky. I made tremendous progress after the hackathon in loading the C* data into graph and then running the recommendation engine against it. But what you really want is for graph to be updated whenever new entries are added in C*. I started working on that, but ran into a fair bit of trouble. 

Then I shelved what I had and didn't have a chance to come back to it. I'll try to make some time this weekend.

**Comment by SonicDMG** [comment]
I was able to integrate Sandeep's work into the KillrVideo java codebase and it is working just fine.  Dude, you saved me so much time.  Thank you.
