### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by publicocean0** [KillrVideo/killrvideo-java#20]
hi i have some questions. 
1) i imported project in intellidea. There is a lot of classes missing : for example import `killrvideo.comments.CommentsServiceOuterClass.CommentOnVideoRequest;`

2) is possible to define a property Map<String,Object> (unstructured and dynamic model) and search for a specific property map?

**Comment by SonicDMG** [comment]
Hi there publicocean0, I am so sorry I am now just getting back to you.  Even though I have notifications on I somehow missed your questions.

As for #1, that class (and others like it) should be generated on a maven compile.  Could you kick that off and let me know if that worked for you?

#2 Could you give me an example of the code area you are working on in reference to your question?

**Comment by markk12** [comment]
I left cassadra because there are too many limitations. I m working on my database. I hope to reach fastly this result.

**Comment by SonicDMG** [comment]
Hi there, good morning.  Ok, so if you are no longer working with Cassandra
I assume you are no longer using KillrVideo?  What kind of limitations were
you running into if you don't mind me asking?
